version: '3.9'

# Секция, где перечислены все сервисы, с которые относятся к системе
services:
  chat_service:
# Путь до Dockerfile сервиса
    build: services/chat_service
    container_name: chat_service
    image: ilfidev/chat_service:latest
    network_mode: host
  # Даём доступ к 80 порту внутри контейнера через 8000 на машине
    ports:
      - 8000:8000
    env_file:
      - ./.env-prod
    # Передаём переменные окружения, которые будут использованы приложением

  contacts:
    build: services/Contacts
    container_name: contacts_service
    image: ilfidev/contacts_service:latest
    network_mode: host
    ports: 
      - 8001:8001
    env_file:
      - ./.env-prod

  registration:
    build: services/Authenticate_user
    container_name: registration_service
    image: ilfidev/registration_service:latest
    network_mode: host
    ports: 
      - 8002:8002
    env_file:
      - ./.env-prod
# Перед запуском этого сервиса ждём пока запустится БД
